Added JsonPointerMatcher
opensearch-project/data-prepper pull request #1091
Opened 2022-02-24 21:09 UTC by sbayer55

Signed-off-by: Steven Bayer <smbayer@amazon.com>

### Description
Added JsonPointerMatcher
 
### Issues Resolved
n/a
 
### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2022-02-24 23:01 UTC, asifsmohammed approved these changes

2022-02-24 23:12 UTC, dlvenable requested changes

2022-02-24 23:12 UTC, dlvenable commented on data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/JsonPointerMatcher.java
> +    //region valid rule order
What is this `//region`?

2022-02-24 23:12 UTC, dlvenable commented on data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/SimpleExpressionMatcher.java
> +    protected static final Matcher<Integer> singleChildMatcher = is(1);
This should use the all upper-case formatting since it is `static final`.

2022-02-24 23:12 UTC, dlvenable commented on data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/JsonPointerMatcher.java
> +    private static final Matcher<ParseTree> terminalNodeMatcher = isTerminalNode();
Please rename to `TERMINAL_NODE_MATCHER` to continue with Java conventions.

2022-02-24 23:13 UTC, graytaylor0 submitted a review, later dismissed

2022-02-25 18:06 UTC, graytaylor0 approved these changes

2022-02-25 19:12 UTC, dlvenable approved these changes

2022-02-25 19:13 UTC, merged