Updates NoOpPrepper to implement Processor
opensearch-project/data-prepper pull request #1142
Opened 2022-03-03 23:29 UTC by sshivanii

### Description
* Updates NoOpPrepper to implement Processor instead of Prepper
 
### Issues Resolved
Contributes to #647 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2022-03-03 23:34 UTC, dlvenable requested changes

2022-03-03 23:34 UTC, dlvenable commented on data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/NoOpPrepper.java
> +    public Collection<Record<Event>> execute(Collection<Record<Event>> records) {
We should keep this `final` here.

2022-03-03 23:34 UTC, dlvenable commented on data-prepper-core/src/test/java/com/amazon/dataprepper/TestDataProvider.java
> +    public static final String VALID_MULTIPLE_PROCESSERS_CONFIG_FILE = "src/test/resources/valid_multiple_processors.yml";
Wow! Nice catch!

2022-03-04 15:50 UTC, dinujoh approved these changes

2022-03-04 17:14 UTC, dlvenable approved these changes

2022-03-04 18:25 UTC, merged