Added Core Peer Forwarder decorator and interface
opensearch-project/data-prepper pull request #1592
Opened 2022-07-14 16:32 UTC by asifsmohammed

Signed-off-by: Asif Sohail Mohammed <nsifmoh@amazon.com>

### Description
Adds core peer forwarder decorator skeleton and interface
 
### Issues Resolved
Resolves #1589 
Resolves #1590 
 
### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2022-07-14 19:20 UTC, chenqi0805 commented on data-prepper-core/src/main/java/com/amazon/dataprepper/peerforwarder/PeerForwardingProcessingDecorator.java
> +public class PeerForwardingProcessingDecorator implements Processor<Record<Event>, Record<Event>> {
Discussed offline: we can push back this until adding metrics

2022-07-14 19:21 UTC, chenqi0805 submitted a review, later dismissed

2022-07-14 19:32 UTC, asifsmohammed commented on data-prepper-core/src/main/java/com/amazon/dataprepper/peerforwarder/PeerForwardingProcessingDecorator.java
> +public class PeerForwardingProcessingDecorator implements Processor<Record<Event>, Record<Event>> {
We need to think about how we can pass `PluginMetrics` to constructor of `PeerForwardingProcessorDecorator`

2022-07-15 19:09 UTC, dlvenable requested changes

2022-07-15 19:09 UTC, dlvenable commented on data-prepper-core/src/main/java/com/amazon/dataprepper/peerforwarder/PeerForwardingProcessorDecorator.java
> +        throw new NotImplementedException();
Java has a built-in exception you can use for now: `UnsupportedOperationException`. You can remove the Apache dependency by making this change.

2022-07-15 19:09 UTC, dlvenable commented on settings.gradle
> +include 'core-peer-forwarder'
You added a new project here. But, I don't see any project files under `core-peer-forwarder`. We can just remove this for now.

2022-07-15 19:21 UTC, chenqi0805 submitted a review, later dismissed

2022-07-19 02:07 UTC, merged