Created CSVProcessor skeleton & CSVProcessorConfig
opensearch-project/data-prepper pull request #1620
Opened 2022-07-25 22:43 UTC by finnroblin

Signed-off-by: Finn Roblin <finnrobl@amazon.com>

### Description
Adds CSV processor plugin skeleton and configuration options.
 
### Issues Resolved

Resolves #1613 

### Check List
- [X] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2022-07-26 02:14 UTC, asifsmohammed requested changes

2022-07-26 02:14 UTC, asifsmohammed commented on data-prepper-plugins/csv-processor/build.gradle
> +    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
Same as above, not required. I think these will be used used from parent project

2022-07-26 02:14 UTC, asifsmohammed commented on data-prepper-plugins/csv-processor/src/main/java/com/amazon/dataprepper/plugins/processor/csv/CSVProcessorConfig.java
> +    private String columnNamesSourceKey;
nit: Please add empty line between variables with annotations for readability like you had it above `quoteCharacter`

2022-07-26 02:14 UTC, asifsmohammed commented on data-prepper-plugins/csv-processor/src/main/java/com/amazon/dataprepper/plugins/processor/csv/CSVProcessorConfig.java
> +    public String[] getColumnNames() { return columnNames;}
Same again please add an empty line between methods for readability. Also, even if methods are one line it's better to have body in new line like below.
```
public String getColumnNamesSourceKey() {
    return columnNamesSourceKey;
}
```

You can use IntelliJ shortcut to create getters. `cmd + n` should give a generate panel where you can select Getter and create getters for required fields.

2022-07-26 02:14 UTC, asifsmohammed commented on data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/codec/NewlineDelimitedCodec.java
> +            // line and the header values.
Not related to this PR.

2022-07-26 02:14 UTC, asifsmohammed commented on data-prepper-config.yaml
> +ssl: false
Can you remove this additional config file?

2022-07-26 16:58 UTC, dlvenable requested changes

2022-07-26 16:58 UTC, dlvenable commented on data-prepper-plugins/csv-processor/src/main/java/com/amazon/dataprepper/plugins/processor/csv/CSVProcessorConfig.java
> +    private String[] columnNames;
Please use `List<String>`. Jackson will know how to deserialize a JSON array into a Java list.

2022-07-26 16:58 UTC, dlvenable commented on data-prepper-plugins/csv-processor/src/main/java/com/amazon/dataprepper/plugins/processor/csv/CSVProcessorConfig.java
> +    public String[] getColumnNames() {
List<String>

2022-07-26 16:58 UTC, dlvenable commented on data-prepper-plugins/csv-processor/src/test/java/com/amazon/dataprepper/plugins/processor/csv/CSVProcessorTest.java
> +    @BeforeEach
Please add a new line above here.

```
private PluginMetrics pluginMetrics;

@BeforeEach
```

2022-07-26 16:58 UTC, dlvenable commented on data-prepper-plugins/csv-processor/src/main/java/com/amazon/dataprepper/plugins/processor/csv/CSVProcessor.java
> +
You don't need this line.

2022-07-26 16:58 UTC, dlvenable commented on data-prepper-plugins/csv-processor/src/main/java/com/amazon/dataprepper/plugins/processor/csv/CSVProcessor.java
> + */
Please line up the asterisks. There is a standard Javadoc format for this. Here is an example.

https://github.com/opensearch-project/data-prepper/blob/31bf29b5c562ed74cecd65760c38c0a91edbca00/data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginProvider.java#L10-L16

2022-07-27 21:59 UTC, travisbenedict submitted a review, later dismissed
LGTM just a couple small unimportant things.

2022-07-27 21:59 UTC, travisbenedict commented on data-prepper-plugins/csv-processor/src/test/java/com/amazon/dataprepper/plugins/processor/csv/CSVProcessorConfigTest.java
> +        CSVProcessorConfig objectUnderTest = createObjectUnderTest();
nit: this could be `final CSVProcessorConfig...`

2022-07-27 21:59 UTC, travisbenedict commented on data-prepper-plugins/csv-processor/src/test/java/com/amazon/dataprepper/plugins/processor/csv/CSVProcessorConfigTest.java
> +        final CSVProcessorConfig csvProcessorConfig = new CSVProcessorConfig();
Could make this `final CSVProcessorConfig csvProcessorConfig = createObjectUnderTest();` for consistency

2022-07-27 22:49 UTC, travisbenedict submitted a review, later dismissed

2022-07-28 02:02 UTC, dlvenable approved these changes

2022-07-28 05:16 UTC, asifsmohammed commented on data-prepper-plugins/csv-processor/src/test/java/com/amazon/dataprepper/plugins/processor/csv/CSVProcessorConfigTest.java
> +        @BeforeEach
nit: this method is not required. And add empty lines above and below methods.

2022-07-28 16:05 UTC, asifsmohammed approved these changes

2022-07-28 18:47 UTC, merged