Bug Fix: S3 source key
opensearch-project/data-prepper pull request #1926
Opened 2022-10-15 19:18 UTC by asifsmohammed

Signed-off-by: Asif Sohail Mohammed <nsifmoh@amazon.com>

### Description
This PR fixes the bug in S3 source where keys with spaces are not decoded correctly. 

I tested it locally with and without the code change. Also made changes to `SqsWorkerIT` to have space in the key. Tested the IT also with and without the changes to verify.

```
 ./gradlew :data-prepper-plugins:s3-source:integrationTest --tests "org.opensearch.dataprepper.plugins.source.SqsWorkerIT" -Dtests.s3source.region=us-east-1 -Dtests.s3source.bucket=<bucket-name> -Dtests.s3source.queue.url=<queue-url>
```

 
### Issues Resolved
resolves #1923 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2022-10-15 20:43 UTC, dlvenable requested changes
Nice! Thanks!

We should have a unit test for this in `SqsWorkerTest`. In general bug fixes are often good candidates for unit tests since we often have a concrete example of what to do and not do. It can verify that the object reference uses the `getUrlDecodedKey()` instead of `getKey()`. Perhaps you mock them to return different values.

I also think the integration test should be distinct. But, I'm fine accepting the PR without that change.

2022-10-15 22:33 UTC, asifsmohammed commented
I tried adding nit test but this method `populateS3Reference` is nested with in 3 levels of private methods. I can make this method package private and test it. Let me know if there's a better approach here for unit testing.

2022-10-15 23:57 UTC, dlvenable approved these changes

2022-10-15 23:57 UTC, dlvenable commented on data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java
> +        final Method method = SqsWorker.class.getDeclaredMethod("populateS3Reference", S3EventNotification.S3EventNotificationRecord.class);
You can also make this method package protected specifically for testing purposes. I do think there is probably some opportunity for refactoring, but this should work for now.

2022-10-18 20:29 UTC, sshivanii commented on data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java
> +        // Using reflection to unit test a private method as part of bug fix.
Minor and non-blocking: It makes sense to include a link to the Bug for future reference

2022-10-18 20:48 UTC, sshivanii approved these changes

2022-10-18 21:54 UTC, cmanning09 commented on data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java
> +    void populateS3Reference_should_interact_with_getUrlDecodedKey() throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
Can we not test an s3Entity with a key that has a space in it? Why do we need reflection?

2022-10-19 16:39 UTC, merged