Add when condition to aggregate processor
opensearch-project/data-prepper pull request #2018
Opened 2022-11-16 20:11 UTC by kkondaka

Signed-off-by: Krishna Kondaka <krishkdk@amazon.com>

### Description
Add support to conditionally aggregate based on user configured condition.

Added "when:" configuration option to aggregate processor. 

With this change, the aggregate processor configuration could look like the following to do the aggregation only when the sourceIp is "10.10.10.10"

```
 - aggregate:
        identification_keys: ["sourceIp", "destinationIp", "port"]
        action:
          remove_duplicates:
        when: "/sourceIp == 10.10.10.10"
```

 
### Issues Resolved
This addresses part of issue #2015
 
### Check List
- [ X] New functionality includes testing.
- [ X] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2022-11-16 21:36 UTC, dlvenable requested changes

2022-11-16 21:36 UTC, dlvenable commented on data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java
> +            final String eventKey = "key";
I think that these values don't matter. That is, the actual value "key" could be anything. Please use a random string to help make it clearer that these values don't matter.

The same applies to the condition which is not actually evaluated and only mocked.

2022-11-16 21:36 UTC, dlvenable commented on data-prepper-plugins/aggregate-processor/README.md
> +* `when` (Optional): A `String` that represents a condition that must be evaluated to true for the aggregation to be applied on the event. Events that do not evaluate to true on the condition are ski
> Default is no condition.

Maybe be a little more explicit: " Default is no condition which means all events are included in the aggregation."

2022-11-16 21:36 UTC, dlvenable commented on data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
> +    private String whenCondition;
Please make this `final`.

2022-11-16 21:36 UTC, dlvenable commented on data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java
> +            assertThat(recordsOut.size(), equalTo(2));
You should verify that this has the expected elements in it.

2022-11-17 00:13 UTC, kkondaka commented on data-prepper-plugins/aggregate-processor/README.md
> +* `when` (Optional): A `String` that represents a condition that must be evaluated to true for the aggregation to be applied on the event. Events that do not evaluate to true on the condition are ski
Will go with "`aggregate_when`"

2022-11-17 14:58 UTC, dlvenable approved these changes

2022-11-17 17:29 UTC, dlvenable requested changes
@kkondaka , This build is failing with unused import errors. Please see the build logs.

2022-11-18 21:31 UTC, merged