Added path support for HTTP source
opensearch-project/data-prepper pull request #2277
Opened 2023-02-14 20:22 UTC by asifsmohammed

### Description
- Adds `path` option to HTTP source
- Updated grok e2e to verify the change
 
### Issues Resolved
Resolves #2258 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-02-14 22:19 UTC, dlvenable requested changes

2023-02-14 22:19 UTC, dlvenable commented on data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSource.java
> +            final String httpSourcePath = sourceConfig.getPath().replace("${PIPELINE_NAME}", pipelineName);
Let's use `${pipelineName}` to match with other parameter naming conventions.

2023-02-14 22:19 UTC, dlvenable commented on data-prepper-plugins/http-source/README.md
> +* path (Optional) => A `string` which represents the URI path for log ingestion, and it should start with `/`. Path can contain `${PIPELINE_NAME}` placeholder which will be replaced with pipeline nam
Please use `${pipelineName}` instead of `${PIPELINE_NAME}`.

2023-02-15 02:25 UTC, dlvenable approved these changes

2023-02-27 21:11 UTC, kkondaka approved these changes
Looks good to me.

2023-02-27 21:26 UTC, merged