Initial commit for OTel trace path changes
opensearch-project/data-prepper pull request #2297
Opened 2023-02-21 19:18 UTC by asifsmohammed

### Description
Adds path to oTel trace source. With this change the following are possible
gRPC, HTTP - /opentelemetry.proto.collector.trace.v1.TraceService/Export
HTTP - custom path
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-02-22 03:16 UTC, dlvenable reviewed
Thanks! This looks promising. Please add some tests which include the authentication enabled to ensure that it works with the new service interceptors.

2023-02-28 14:26 UTC, dlvenable requested changes

2023-02-28 14:26 UTC, dlvenable commented on data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java
> +    void gRPC_with_auth_request_writes_to_buffer_with_successful_response() throws Exception {
We should have a test like this which includes the custom path. It should verify that the path is secured.

2023-02-28 14:26 UTC, dlvenable commented on data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java
> +        when(httpBasicAuthenticationConfig.getUsername()).thenReturn(USERNAME);
Please add a test which verifies the path when using authentication.

2023-02-28 14:26 UTC, dlvenable commented on data-prepper-plugins/otel-logs-source/src/test/java/com/amazon/dataprepper/plugins/source/otellogs/OTelLogsSourceTest.java
> +        when(httpBasicAuthenticationConfig.getUsername()).thenReturn(USERNAME);
As with other comments, please verify that `http_basic` works with the custom path.

2023-02-28 19:42 UTC, chenqi0805 approved these changes

2023-03-01 01:53 UTC, dlvenable approved these changes

2023-03-01 01:57 UTC, merged