Fix: Fixed IllegalArgumentException in PluginMetrics
opensearch-project/data-prepper pull request #2369
Opened 2023-03-09 15:48 UTC by asifsmohammed

### Description
- Reverted some of the changes made in https://github.com/opensearch-project/data-prepper/pull/2297 which is passing  null Plugin Name
 
### Issues Resolved
resolves #2368 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-03-09 16:33 UTC, dlvenable requested changes
Thanks for working this!

I'd like to avoid similar things from happening again. There is a minor design issue which makes it easy to write incorrect code in this situation. I see two solutions off the bat:

(I'll reference line numbers in OTelTraceSource)

1. Swap the order one lines 76 and 77 from:

```
this.authenticationProvider = createAuthenticationProvider(pluginFactory, pipelineDescription);
this.pipelineName = pipelineDescription.getPipelineName();
```

to:

```
this.pipelineName = pipelineDescription.getPipelineName();
this.authenticationProvider = createAuthenticationProvider(pluginFactory, pipelineDescription);
```

2. Make the `createAuthenticationProvider` method (line 213) static. You would have to pass one additional field it, but this is ok.

2023-03-09 18:22 UTC, engechas approved these changes

2023-03-09 18:24 UTC, dlvenable approved these changes
Thanks!

2023-03-09 18:54 UTC, merged

2023-03-10 13:17 UTC, dinujoh commented
Can you update the unit test to assert pluginFactory authenticationPluginSetting contains the pipelineName ?