Support for source codecs | Avro Codec
opensearch-project/data-prepper pull request #2397
Opened 2023-03-23 07:53 UTC by umairofficial

### Description
Avro Codec implementation added with 100% unit test case coverage. 
 
### Issues Resolved
Resolves https://github.com/opensearch-project/data-prepper/issues/1532 : Avro rows now parsed correctly into Event objects, is proper key value pair format. 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-03-27 23:25 UTC, kkondaka requested changes

2023-03-27 23:25 UTC, kkondaka commented on data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroInputCodecTest.java
> +        avroInputCodec=new AvroInputCodec();
This statement is not needed because `setup()` is doing the initialization of `avroInputCodec`

2023-03-27 23:25 UTC, kkondaka commented on data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroInputCodecTest.java
> +        avroInputCodec=new AvroInputCodec();
same here and in all the test cases below.

2023-03-27 23:25 UTC, kkondaka commented on data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroInputCodecTest.java
> +            assertThat(actualRecord.getData(), notNullValue());
Please verify that the events in the records have `person`, `age` and `name` are present and have expected values.

2023-04-07 02:04 UTC, umairofficial commented
Closing this PR is favour of #2414.

2023-04-07 02:04 UTC, closed without merging