Updated package name for otel logs source
opensearch-project/data-prepper pull request #2518
Opened 2023-04-18 04:58 UTC by asifsmohammed

### Description
- Updates the package name of otel_logs_source from `com.amazon.dataprepper` to `org.opensearch.dataprepper` which was missed during plugin migration and 2.1 release
 
### Issues Resolved
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-04-18 19:08 UTC, oeyh approved these changes

2023-04-18 20:04 UTC, dlvenable requested changes

2023-04-18 20:04 UTC, dlvenable commented on data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/PluginPackagesSupplier.java
> -    // TODO: Remove this once all plugins have migrated to org.opensearch
Let's remove this support in Data Prepper 3.0. Please revert these data-prepper-core changes for now.

2023-04-19 18:56 UTC, dlvenable approved these changes

2023-04-19 21:59 UTC, merged