Opensearch serverless change
opensearch-project/data-prepper pull request #2542
Opened 2023-04-19 21:58 UTC by asifsmohammed

### Description
- Removed `aws_serverless` option and serverless can only be enabled by `aws` option.
- Updated documentation
 
### Issues Resolved
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-04-19 22:15 UTC, dlvenable requested changes
What is the problem with keeping this option?

2023-04-19 22:15 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java
> +//    @Test
Please remove commented out code. There is no need for it to remain.

2023-04-19 22:16 UTC, engechas reviewed
Isn't this a breaking change?

2023-04-19 22:35 UTC, asifsmohammed commented
> What is the problem with keeping this option?

Since `aws_` options are outdated and serverless is not released yet. We don't want to support legacy way of configuring serverless.

2023-04-19 22:36 UTC, asifsmohammed commented
> Isn't this a breaking change?

No, serverless is not released yet. If existing users who are using `aws_sigv4` to enable sigv4 are required to use `aws` option if only they want to enable serverless.

2023-04-20 02:03 UTC, asifsmohammed commented
Build is passing locally.

2023-04-20 04:31 UTC, kkondaka approved these changes

2023-04-20 14:28 UTC, merged