Log clear messages when OpenSearch Sink fails to push. Modify retries to be iterative instead of recursive
opensearch-project/data-prepper pull request #2605
Opened 2023-04-28 22:09 UTC by kkondaka

### Description
Log clear messages when OpenSearch Sink fails to push. Modify retries to be iterative instead of recursive.
Logs failure messages after every 5 retries and also after last retry.
Modified retry logic to be iterative instead of recursive.
 
Resolves #2597 
### Issues Resolved
#2597 
 
### Check List
- [X ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-05-01 16:42 UTC, chenqi0805 submitted a review, later dismissed

2023-05-01 18:35 UTC, dlvenable requested changes
Nice! Thanks! I just have one small comment.

2023-05-01 18:35 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
> +    class BulkOperationRequestResponse {
This should be `static` since it doesn't need anything from the current `BulkRetryStrategy`.

2023-05-02 01:44 UTC, dlvenable commented
@kkondaka , The OpenSearch sink integration tests are all failing. There appears to be something wrong with this change.

2023-05-02 21:26 UTC, dlvenable approved these changes

2023-05-02 22:26 UTC, chenqi0805 approved these changes

2023-05-02 23:05 UTC, merged