Added Readme.md
opensearch-project/data-prepper pull request #2714
Opened 2023-05-19 12:09 UTC by ajeeshakd

### Description
- Added the Readme.md file
 
### Issues Resolved
- Github issue https://github.com/opensearch-project/data-prepper/issues/254
 
### Check List
- [ ] Includes Readme.md.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-05-19 20:48 UTC, ashoktelukuntla approved these changes
Looks good

2023-05-25 17:38 UTC, dlvenable submitted a review, later dismissed

2023-06-21 16:13 UTC, kkondaka requested changes

2023-06-21 16:13 UTC, kkondaka commented on data-prepper-plugins/kafka-plugins/README.md
> +- `auth_type` (Optional) : The auth_type directive selects the method that is used to authenticate the user. There is no auth type by default. The most common supported methods are SASL_PLAINTEXT,SAS
same here.

2023-06-21 18:49 UTC, merged