Opensearch Source Boilerplate code for #1985,2264.
opensearch-project/data-prepper pull request #2734
Opened 2023-05-23 14:21 UTC by mallikagogoi7

### Description
Opensearch Source Boilerplate code
 
### Issues Resolved
#1985,2264
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-05-23 19:50 UTC, dlvenable requested changes
Thanks for this contribution @mallikagogoi7 !

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/model/PITBuilder.java
> +public  class PITBuilder implements ObjectBuilder<PITRequest> {
Please rename this class to `PitBuilder`.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/model/PITRequest.java
> +public class PITRequest implements JsonpSerializable {
Please rename to `PitRequest`.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/model/PITResponse.java
> +public class PITResponse  {
Please update to `PitResponse`.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchClientBuilder.java
> +    public ElasticsearchClient createElasticSearchCLient(final URL url) {
Correct the case of the `L` in `CLient` to `Client`.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceService.java
> +        sourceConfig.getHosts().forEach(host ->{
The hosts should be shared and provided to the OpenSearch Java client.

These `hosts` represent the different hosts which make up the OpenSearch cluster. They should not have their own schedules.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/model/DeletePITResponse.java
> +public class DeletePITResponse implements Serializable {
Please rename to `DeletePitResponse`.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/model/DeletePITResponse.java
> +        public String getPit_id() {
Should be `getPitId`.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/model/DeletePITResponse.java
> +        public void setPit_id(String pit_id) {
Should be `setPitId`

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/model/Hit.java
> +public class Hit {
Is this different from `org.opensearch.client.opensearch.core.search.Hit`? Can we not use that?

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/model/Hits.java
> +public class Hits {
The `org.opensearch.client.opensearch.core.search` package has some models for hits. Can we use any of those?

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/model/PITRequest.java
> +    public static final Endpoint<PITRequest, Map, ErrorResponse> ENDPOINT =
This should have unit tests.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/model/PITRequest.java
> +public class PITRequest implements JsonpSerializable {
This whole class can have unit tests.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/model/PITResponse.java
> +    public static JsonpDeserializer<PITResponse> PARSER;
Do we need this? And if so, how can we better hide it?

Using public variable fields is often not recommended.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/service/BackoffService.java
> +public class BackoffService {
Armeria has a class `Backoff`:

```
com.linecorp.armeria.client.retry.Backoff
```

Let's use this.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/service/OpenSearchService.java
> +    public String getPITId(final String index){
Rename to `getPitId`

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/service/OpenSearchService.java
> +    public Map<String, Object> searchIndexesByPITId(final String pitId) {
Rename to `searchIndexesByPitId`

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/service/OpenSearchService.java
> +    public Map<String, Object> searchIndexesByPITIdForPagination(final String pitId) {
`searchIndexesByPitIdForPagination`

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/service/OpenSearchService.java
> +    public boolean deletePITId(String pitId) {
Rename to `deletePitId`

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/OpenSearchTimerWorker.java
> +            if (OPEN_SEARCH_DISTRIBUTION.equals(serviceInfo.getDistribution())) {
Let's avoid this condition in this class`.

Please inject a strategy into this class via the constructor. Then you will have a single mechanism for processing indexes.

You will inject a `CommonSearchService` in this class.

This code then becomes:

```
@Override
public void run() {
  for(int jobCount=1 ; sourceConfig.getSchedulingParameterConfiguration().getJobCount() >= jobCount; jobCount++) {
    commonSearchService.processIndexes(serviceInfo.getVersion(),
                        getIndexList(),
                        host,
                        sourceConfig.getSearchConfiguration().getBatchSize());
```

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/service/OpenSearchService.java
> +public class OpenSearchService {
Please create an interface to abstract this and `ElasticSearchService`.

```
public interface CommonSearchService {
  void processIndexes(final Integer version,
                               final String indexList,
                               final String url,
                               final Integer batchSize)
}
```

I'm open to a better name than `CommonSearchService`.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/service/OpenSearchService.java
> +    public void processIndexes(final Integer version,
This needs unit testing.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/OpenSearchTimerWorker.java
> +    private String getIndexList()
Let's move this into a different class specifically for determining the indexes.

You can also add quality unit tests to such a class.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/OpenSearchTimerWorker.java
> +public class OpenSearchTimerWorker extends TimerTask {
This class needs unit tests.

2023-05-23 19:50 UTC, dlvenable commented on data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/codec/JacksonValueParser.java
> +public class JacksonValueParser<T> extends JsonpDeserializerBase<T> {
This class needs unit tests.

2023-06-02 15:55 UTC, cmanning09 commented
@mallikagogoi7, thanks for your contribution. We have restructured this plugin and this change is no longer needed. I am going to close this contribution.

2023-06-02 15:55 UTC, closed without merging