Update RCF Maven version to reduce noise
opensearch-project/data-prepper pull request #2784
Opened 2023-05-30 20:49 UTC by kkondaka

### Description
Updates RCF maven version to 3.7. This version of RCF has some fixes to reduce noise (low grade anomalies)

Resolves #2783 
 
### Issues Resolved
#2783 
 
### Check List
- [X ] New functionality includes testing.
- [X ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-05-30 21:29 UTC, sudiptoguha approved these changes

2023-05-31 15:06 UTC, dlvenable requested changes

2023-05-31 15:06 UTC, dlvenable commented on data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/modes/RandomCutForestMode.java
> +        System.out.println("..."+this.sampleSize+"..."+this.shingleSize+"..."+this.outputAfter);
Please remove this. Feel free to use a `LOG.trace` if you'd like.

2023-05-31 19:05 UTC, dlvenable approved these changes

2023-05-31 19:06 UTC, sudiptoguha approved these changes

2023-05-31 19:22 UTC, merged