Define multiple keys for type conversion
opensearch-project/data-prepper pull request #2934
Opened 2023-06-26 07:24 UTC by wanghd89

### Description
Allow defining multiple keys in the convert_entry_type processor.

eg: 
```
processor:
    - convert_entry_type:
         keys: ["key1", "key2"]
         type: "integer"
```
 
converts 
`{"message":"value","key1":"123", "key2":"456"}
`
to  
`{"message":"value","key1":123, "key2":456}
`

### Issues Resolved
[2823]
 
### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-06-28 16:52 UTC, asifsmohammed requested changes
Changes looks good, just missing the documentation

2023-06-29 01:49 UTC, wanghd89 commented
> Changes looks good, just missing the documentation

Ok, updated README

2023-06-29 15:09 UTC, oeyh approved these changes

2023-07-05 02:41 UTC, asifsmohammed approved these changes

2023-07-05 02:42 UTC, merged