ENH: support es 6 in sink
opensearch-project/data-prepper pull request #3045
Opened 2023-07-19 15:37 UTC by chenqi0805

### Description
This PR adds support for bulk API with ES 6 backend. 
 
### Issues Resolved
Resolves #3003 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-07-20 14:57 UTC, dlvenable requested changes

2023-07-20 14:57 UTC, dlvenable commented on data-prepper-plugins/opensearch/README.md
> +- `backend_version`: A String indicating whether the sink backend version is Elasticsearch 6 or above (i.e. Elasticsearch 7.x or OpenSearch). `es_6` represents Elasticsearch 6; `null` represents Elas
Maybe name this `distribution_version`? That might be closer to the terms used in OpenSearch itself which uses "distribution" and "version".

2023-07-20 14:57 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BackendVersion.java
> +    ES6("es_6");
Thoughts on dropping the "_": `es6`?

Also, we should probably have some explicit options for users to provide for other version.

Perhaps:
* `es6`
* `es7`
* `os1`
* `os2`

How would we like to support newer OS versions as they are added? Maybe a `default` option which aims for the latest? Thus:

* `es6`
* `default`

2023-07-20 14:57 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/BulkAPIWrapper.java
> +    public BulkResponse bulk(BulkRequest request) throws IOException, OpenSearchException {
We should probably split these classes.

Have an interface for `BulkApiWrapper`. Then have a factory which produces either an `Es6BulkApiWrapper` or an `OpenSearchDefaultBulkApiWrapper`.

Then you can drop this conditional.

And you separate the code that is for ES6 entirely from the code for other versions.

2023-07-20 14:57 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
> +    bulkAPIWrapper = new BulkAPIWrapper(openSearchSinkConfig.getIndexConfiguration(), filteringOpenSearchClient);
See my comment below. Let's get this from a factory.

```
bulkApiWrapper = BulkApiWrapperFactory.getWrapper(openSearchSinkConfig.getIndexConfiguration(), filteringOpenSearchClient);
```

2023-07-24 15:58 UTC, graytaylor0 submitted a review, later dismissed

2023-07-24 18:11 UTC, dlvenable requested changes

2023-07-24 18:11 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/BulkApiWrapperFactoryTest.java
> +        when(indexConfiguration.getDistributionVersion()).thenReturn(DistributionVersion.ES6);
This is testing the ES6 distribution. Perhaps a copy-paste error.

2023-07-24 18:11 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/Es6BulkApiWrapper.java
> +                    final String index = request.index() == null ? DUMMY_DEFAULT_INDEX : request.index();
Should we have this condition? If the request doesn't have an index, perhaps we should fail. Otherwise, the data goes into an index named `dummy`.

2023-07-24 19:38 UTC, dlvenable approved these changes

2023-07-24 20:52 UTC, merged