Add Support for OTel Log SeverityText (#3280)
opensearch-project/data-prepper pull request #3281
Opened 2023-08-29 09:21 UTC by KarstenSchnitter

The OpenTelemetry Codec lacks support for the severity text. This oversight is corrected by extracting the field from the OTLP source data and copying it to a matching field in the JSON document. It tightly aligns with the already supported SeverityNumber field. This closes a gap in the OTLP logs data model mapping. Unit tests of codec and JSON mapping are adjusted for the added field.

### Description
The OpenTelemetry Codec lacks support for the severity text. This oversight is corrected by extracting the field from the OTLP source data and copying it to a matching field in the JSON document. It tightly aligns with the already supported `severityNumber` field. 

### Issues Resolved
Resolves #3280 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-08-29 14:50 UTC, dlvenable requested changes
Thanks @KarstenSchnitter - The only real comment is about when this was added.

Do you need a backport for 2.4.1? (Again, we don't have current plans for such a patch)

2023-08-29 17:39 UTC, KarstenSchnitter commented
I do not think this needs to be back-ported. I would be happy with a 2.5 release. When do you expect that to be released?

2023-08-29 20:45 UTC, dlvenable commented
> I do not think this needs to be back-ported. I would be happy with a 2.5 release. When do you expect that to be released?

@KarstenSchnitter , We are expecting mid October for 2.5.

2023-08-30 17:03 UTC, dlvenable approved these changes

2023-08-30 17:21 UTC, chenqi0805 approved these changes

2023-08-30 17:53 UTC, merged

2023-08-30 17:53 UTC, dlvenable commented
Thank you @KarstenSchnitter !