Fix NPE in s3 scan partition supplier
opensearch-project/data-prepper pull request #3317
Opened 2023-09-08 18:59 UTC by graytaylor0

### Description
Fixes a potential NPE in the s3 scan partition supplier
 
### Issues Resolved
Resolves #3316 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-09-08 19:32 UTC, dlvenable requested changes

2023-09-08 19:32 UTC, dlvenable commented on data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java
> +        Instant mostRecentLastModifiedTimestamp = globalStateMap.containsKey(bucket) && Objects.nonNull(globalStateMap.get(bucket)) ? Instant.parse((String) globalStateMap.get(bucket)) : null;
`globalStateMap.containsKey(bucket) && Objects.nonNull(globalStateMap.get(bucket)) ` can simplify to `globalStateMap.get(bucket) != null`

Also, `Objects.nonNull` is not necessary here. It is intended for use where a `Predicate` is needed.

2023-09-08 20:12 UTC, dlvenable approved these changes

2023-09-08 20:12 UTC, dlvenable commented
@graytaylor0 , We should probably have a unit test here as well.

2023-09-11 17:05 UTC, dlvenable approved these changes

2023-09-11 18:58 UTC, oeyh approved these changes

2023-09-12 15:09 UTC, merged