Disable flaky e2e acks test
opensearch-project/data-prepper pull request #3471
Opened 2023-10-10 15:39 UTC by kkondaka

### Description
Disabling flaky test in e2e acks integration test
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ X] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-10-10 16:01 UTC, dlvenable requested changes
Please create a GitHub issue to track adding this back in. Set the milestone for 2.6 so that we can track it.

2023-10-10 17:26 UTC, kkondaka commented
@dlvenable created the issue https://github.com/opensearch-project/data-prepper/issues/3472 and put milestone as v2.6

2023-10-10 17:26 UTC, dlvenable approved these changes

2023-10-11 17:05 UTC, dlvenable requested changes

2023-10-11 17:05 UTC, dlvenable commented on data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java
> +	System.out.println("Data Prepper Test with config file "+ configFile + " started at "+Instant.now());
Please change this to an SLF4J log line.

```
LOG.info("PipelinesWithAcksIT with configu file {} started at {}", configFile, Instant.now());
```

2023-10-11 17:05 UTC, dlvenable commented on data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java
> +	System.out.println("Data Prepper Test stopped at "+Instant.now());
Again, use SLF4J.

2023-10-11 17:05 UTC, dlvenable commented on data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySource.java
> +                        Thread.sleep(50);
Nice!

2023-10-11 17:08 UTC, graytaylor0 commented
Just a callout I created this issue earlier for flaky tests (https://github.com/opensearch-project/data-prepper/issues/3481)

2023-10-11 18:43 UTC, graytaylor0 approved these changes

2023-10-11 18:56 UTC, dlvenable approved these changes

2023-10-11 19:21 UTC, merged