Integration tests for confluent kakfa
opensearch-project/data-prepper pull request #3476
Opened 2023-10-10 22:39 UTC by kkondaka

### Description
Added integration tests for Confluent kafka
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ X] New functionality includes testing.
- [X ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-10-11 15:41 UTC, dlvenable requested changes
At a high level, do we want to have integration tests which rely on Confluent resources? We need to get to the point where our integration tests run in GitHub, and this would require adding Confluent resources for those to run.

2023-10-11 15:41 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/README.md
> +./gradlew    data-prepper-plugins:kafka-plugins:integrationTest -Dtests.kafka.bootstrap_servers="pkc-lzvrd.us-west4.gcp.confluent.cloud:9092" -Dtests.kafka.topic_name=<topic-name> -Dtests.kafka.usern
Please replace `pkc-lzvrd.us-west4` with `<confluent-cloud-dns>`.

2023-10-11 15:41 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/ConfluentKafkaProducerConsumerWithSchemaRegistryIT.java
> +        Thread producerThread = new Thread(() -> {
As with my comment above - can we drop the threads? Typically tests should avoid using threads whenever possible.

2023-10-11 15:41 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/ConfluentKafkaProducerConsumerWithSchemaRegistryIT.java
> +        for (int i = 0; i < 150; i++) {
Similar to my comments above. I think you don't need any of this. Use Awaitility.

2023-10-11 15:41 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/ConfluentKafkaProducerConsumerWithSchemaRegistryIT.java
> +        Thread producerThread = new Thread(() -> {
Same as other thread comments.

2023-10-11 15:41 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/ConfluentKafkaProducerConsumerWithSchemaRegistryIT.java
> +            e.printStackTrace();
Same as above.

2023-10-11 19:43 UTC, kkondaka commented
> At a high level, do we want to have integration tests which rely on Confluent resources? We need to get to the point where our integration tests run in GitHub, and this would require adding Confluent resources for those to run.

I do not think we can run these in GitHub but it is valuable to have this because we do not have a way to make sure Confluent Kafka works. Manually running these would give some idea on how to use Confluent Kafka with DataPrepper

2023-10-16 15:42 UTC, dlvenable submitted a review, later dismissed
Nice, thanks! This is more readable in my view.

2023-10-18 13:16 UTC, dlvenable approved these changes

2023-10-18 18:46 UTC, dlvenable approved these changes

2023-10-18 19:58 UTC, graytaylor0 approved these changes

2023-10-18 20:08 UTC, merged