Enable acknowledgements for KafkaBuffer plugin
opensearch-project/data-prepper pull request #3584
Opened 2023-11-03 01:16 UTC by hshardeesi

### Description
Enable acknowledgements for KafkaBuffer plugin
 
### Issues Resolved
Enables acknowledgements for kafka buffer, which is currently disabled.

2023-11-03 03:21 UTC, kkondaka approved these changes

2023-11-03 16:19 UTC, dlvenable approved these changes

2023-11-03 16:20 UTC, dlvenable requested changes
The DCO is failing.

2023-11-03 16:23 UTC, dlvenable commented
@hshardeesi , The sign-off is missing. Please see the following guide.

https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-dco

You can edit your commit by adding the `Signed-off-by:`. The force-push it. Please be sure that the email in the `Signed-off-by:` is the same as the email provided in your commit.

2023-11-06 17:56 UTC, dlvenable approved these changes

2023-11-06 17:57 UTC, merged