Add splitExportTraceServiceRequest API to OTelProtoDecoder
opensearch-project/data-prepper pull request #3600
Opened 2023-11-08 07:04 UTC by kkondaka

### Description
Add splitExportTraceServiceRequest API to OTelProtoDecoder.
This API splits ExportTraceServiceRequest to multiple ExportTraceServiceRequests, one per unique traceId. After the split, each ExportTraceServiceRequests will contain only spans belonging to same traceId.
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ X] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [X ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-11-09 08:52 UTC, chenqi0805 submitted a review, later dismissed

2023-11-09 18:28 UTC, dlvenable requested changes
I'd like to reconsider our approach here.

As I understand it, the goal of this is to route different traces in Kafka rather than have to forward it over HTTP in the peer-forwarder later.

As we are having to parse the binary and then recreate, I think we can improve this approach by just saving Events to the Kafka buffer. We can take any event or collection of events and then serialize those.

This approach would also solve the problem for other sources so that they can work with the `kafka` buffer without having to update to use `byte[]`.

2023-11-09 23:20 UTC, dlvenable submitted a review, later dismissed
We discussed offline and agreed to proceed with this approach for now. It is simple enough and solves the current problem.

2023-11-10 04:15 UTC, graytaylor0 approved these changes

2023-11-10 05:09 UTC, merged