Create network policy for aoss source.
opensearch-project/data-prepper pull request #3613
Opened 2023-11-08 21:50 UTC by asuresh8

### Description
Allow AOSS source to create/update a network policy during initialization
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

Tested with:
```
version: "2"
log-pipeline:
  source:
    opensearch:
      hosts: [ "https://cw4c6ujthlys4gf4qp7c.us-east-1.aoss.amazonaws.com" ]
      indices:
        include:
          - index_name_regex: ".*"      
      aws:
        sts_role_arn: "arn:aws:iam::841692598829:role/FizzyE2ETestPipelineExecutionRole"
        region: "us-east-1"
        serverless: true
        serverless_options:
          network_policy_name: "new-adi-test-collection"
          collection_name: "adi-test-collection"
          vpce_id: "vpce-0998c653f94b15f22"
  sink:
    - stdout:
```

2023-11-08 22:46 UTC, dlvenable requested changes

2023-11-08 22:46 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/AwsAuthenticationConfiguration.java
> +    private ServerlessOptions serverless_options;
For the Java variable we should name this `serverlessOptions`. The property name as represented in `@JsonPreoperty` is good and should have the underscore.

2023-11-08 22:46 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
> +    private void maybeUpdateNetworkPolicy() {
This should have some unit tests.

2023-11-09 08:04 UTC, chenqi0805 submitted a review, later dismissed

2023-11-09 18:43 UTC, dlvenable submitted a review, later dismissed

2023-11-09 19:15 UTC, asuresh8 commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
> +    private void maybeUpdateNetworkPolicy() {
Done

2023-11-10 18:26 UTC, dlvenable approved these changes

2023-11-10 19:23 UTC, graytaylor0 approved these changes

2023-11-10 19:23 UTC, graytaylor0 commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
> +            System.out.println("PRESENT!");
Should remove the print statement

2023-11-10 19:31 UTC, dlvenable requested changes

2023-11-10 19:31 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
> +            System.out.println("PRESENT!");
Yes, this is a good catch. Thanks!

2023-11-10 20:00 UTC, asuresh8 commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
> +            System.out.println("PRESENT!");
Thanks for catching! Fixed.

2023-11-10 21:54 UTC, dlvenable approved these changes

2023-11-10 22:08 UTC, graytaylor0 approved these changes

2023-11-10 22:15 UTC, merged