Fix for [BUG] Data Prepper is losing connections from S3 pool
opensearch-project/data-prepper pull request #3836
Opened 2023-12-08 16:03 UTC by kkondaka

### Description
Fix for [BUG] Data Prepper is losing connections from S3 pool.
Root cause for this issue is that the input stream opened in codec is not closed.
 
Resolves #3809 
### Issues Resolved
Resolves #3809 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-12-08 16:28 UTC, dlvenable requested changes

2023-12-08 16:28 UTC, dlvenable commented on data-prepper-api/src/main/java/org/opensearch/dataprepper/model/codec/InputCodec.java
> +        } catch (Exception e) {
Can we make use of `AutoCloseable` and put this in a try-with-resources statement?

```
try(InputStream inputStream = inputFile.newStream()) {
  parse(decompressionEngine.createInputStream(inputStream), eventConsumer);
}
```

2023-12-11 17:56 UTC, dlvenable submitted a review, later dismissed

2023-12-11 19:33 UTC, asifsmohammed submitted a review, later dismissed

2023-12-11 22:55 UTC, dlvenable approved these changes

2023-12-11 23:02 UTC, asifsmohammed approved these changes

2023-12-11 23:07 UTC, merged