Handle stale changeVisibilityTimeout calls
opensearch-project/data-prepper pull request #3859
Opened 2023-12-18 17:38 UTC by kkondaka

### Description
Handle stale changeVisibilityTimeout calls by not logging the error messages and returning different value so that the progress check callbacks can be cleaned up.
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [X ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2023-12-19 15:15 UTC, dlvenable requested changes

2023-12-19 15:15 UTC, dlvenable commented on data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java
> +                                Thread.sleep(40*1000);
Why 40 seconds? Is it related to another constant?

It would be good to make this a constant with a useful name.

2023-12-19 15:15 UTC, dlvenable commented on data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java
> +            //final int progressCheckInterval = visibilityTimeout/2 - 1;
Please remove this commented out code.

2024-04-04 19:42 UTC, chenqi0805 approved these changes

2024-05-13 05:52 UTC, closed without merging