Otel metrics fix
opensearch-project/data-prepper pull request #3998
Opened 2024-01-22 21:29 UTC by kkondaka

### Description
OTEL histograms may contain  bucket counts list with just one entry with no explicit bounds specified. This can cause the current code to not handle it correctly. When the explicit bounds array is empty, -infinity and +infinity should be used as bounds.
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [X ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-01-22 22:14 UTC, dlvenable requested changes

2024-01-22 22:14 UTC, dlvenable commented on data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java
> +                                LOG.debug("Set visibility timeout for message {} to {}", parsedMessage.getMessage().messageId(), newVisibilityTimeoutSeconds);
It looks like you have a commit from your other PR.

2024-01-22 22:14 UTC, dlvenable commented on data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCodec.java
> +            if (bucketCountsList.size() == 1) {
Can you add a unit test which demonstrates the original failure and then shows that this fixes it?

2024-01-22 22:16 UTC, dlvenable requested changes

2024-01-23 14:34 UTC, dlvenable approved these changes
Thanks!

2024-01-23 17:10 UTC, graytaylor0 approved these changes

2024-01-23 17:46 UTC, merged