Update dissect and user_agent readme
opensearch-project/data-prepper pull request #4100
Opened 2024-02-09 18:15 UTC by oeyh

### Description
Update dissect and user_agent readme to refer to documentation website.
 
### Issues Resolved
Part of #2740
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-02-09 19:44 UTC, asifsmohammed approved these changes

2024-02-21 16:35 UTC, graytaylor0 approved these changes

2024-02-21 16:36 UTC, graytaylor0 requested changes
Just saw build is failure you can run this to fix the checkstyle error

```
 * What went wrong:
Execution failed for task ':data-prepper-plugins:user-agent-processor:spotlessMarkdownCheck'.
> The following files had format violations:

      README.md
          @@ -1,4 +1,4 @@
           #·User·Agent·Processor
           This·processor·parses·User-Agent·(UA)·string·in·an·event·and·add·the·parsing·result·to·the·event.
           
          -See·the·[`user_agent`·processor·documentation](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/user-agent/).
          +See·the·[`user_agent`·processor·documentation](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/user-agent/).
  Run './gradlew :data-prepper-plugins:user-agent-processor:spotlessApply' to fix these violations.
```

2024-02-22 16:20 UTC, asifsmohammed approved these changes

2024-02-22 16:21 UTC, graytaylor0 approved these changes

2024-02-22 16:21 UTC, merged