Remote detector calls
opensearch-project/data-prepper pull request #4106
Opened 2024-02-12 07:48 UTC by engechas

### Description
Adds a new implementation of the BulkApiWrapper to hit a security analytics API
 
### Check List
- [x] New functionality includes testing.
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-02-12 19:13 UTC, graytaylor0 approved these changes

2024-02-12 19:27 UTC, kkondaka approved these changes

2024-02-13 18:21 UTC, dlvenable requested changes

2024-02-13 18:21 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/OpenSearchDetectorScanBulkApiWrapperTest.java
> +            assertThat(r.getMethod(), equalTo(DETECTOR_SCAN_API_METHOD));
There is a lot going on in here, and you have a try-catch block.

I think moving to use an `ArgumentCaptor` would help how much is here. And then you won't need that try-catch either.

2024-02-13 18:21 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/OpenSearchDetectorScanBulkApiWrapper.java
> +    public OpenSearchDetectorScanBulkApiWrapper(final RestHighLevelClient restHighLevelClient) {
What would it take to use a `OpenSearchClient` here instead of the RHLC?

2024-02-13 18:21 UTC, dlvenable commented on data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
> +                        if (RestStatus.FAILED_DEPENDENCY.getStatus() == bulkItemResponse.status()) {
How hard would it be to test these conditions? If not too hard, let's verify the behavior.

2024-03-07 18:01 UTC, graytaylor0 submitted a review, later dismissed
Looks good. Am interested to hear of the performance implications/improvements here once some performance testing is done.

2024-03-08 20:26 UTC, kkondaka approved these changes

2024-09-10 20:12 UTC, closed without merging