Catch exceptions instead of throwing for processors that can handle Events event by event
opensearch-project/data-prepper pull request #4162
Opened 2024-02-20 16:25 UTC by graytaylor0

### Description
This change makes it so any processors (other than stateful processors) will catch runtime exceptions for individual Events, and then log the error and tag the Event, before continuing on to the next Event.

This included the following processors

* csv
* dissect
* key_value
* convert_entry_type
* mutate events processors
* mutate string processors
* map_to_list
* obfuscate
* truncate
 
### Issues Resolved
Related to #4103
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-02-20 16:51 UTC, dlvenable approved these changes

2024-02-20 16:52 UTC, dlvenable commented
What would it take to get some unit tests for these scenarios?

2024-02-20 16:56 UTC, graytaylor0 commented
> What would it take to get some unit tests for these scenarios?

It would be pretty tedious to add to each processor, but could be easier to add by just mocking expression evaluator to throw for processors that use it

2024-02-20 21:54 UTC, dlvenable approved these changes

2024-02-20 22:05 UTC, dlvenable commented
@graytaylor0 , It appears that this build is still failing.

> error: 'catch' without 'try'

2024-02-20 22:05 UTC, dlvenable requested changes
Fix failing build

2024-02-21 16:55 UTC, dlvenable approved these changes

2024-02-21 17:17 UTC, oeyh approved these changes
Thanks for making it consistent throughout processors.

2024-02-21 17:18 UTC, merged