Refactor PipelinesDataFlowModelParser to take in an InputStream instead of a file path
opensearch-project/data-prepper pull request #4289
Opened 2024-03-14 23:43 UTC by graytaylor0

### Description
This change refactors the `PipelinesDataFlowModelParser` to not be dependent on files, but to be dependent on `InputStreams`. 

This is done with

* An interface `PipelineConfigurationReader` that is passed to the `PipelinesDataFlowModelParser`. 
* An implementation `PipelineConfigurationFileReader` that is created via dependency injection, and contains the former chunk s of `PipelinesDataFlowModelParser` that was relevant to reading the files
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-03-15 14:32 UTC, chenqi0805 reviewed
change looks good to me. Question -- What is the motivation for this change?

2024-03-18 15:21 UTC, graytaylor0 commented
> change looks good to me. Question -- What is the motivation for this change?

The motivation is to make this library extendible to support non-files, such as raw strings of the pipeline config

2024-03-19 15:10 UTC, dlvenable requested changes
This is a very nice improvement to this code. Thanks!

I do have one comment about exceptions that we should resolve.

2024-03-19 15:10 UTC, dlvenable commented on data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationFileReader.java
> +                    .filter(Objects::nonNull).collect(Collectors.toList());
In this case, I think we should throw an exception since we are looking for a single file.

2024-03-19 15:50 UTC, dlvenable requested changes

2024-03-19 15:50 UTC, dlvenable commented on data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationFileReader.java
> +            LOG.warn("Pipeline configuration file {} not found", pipelineConfigurationFile.getName());
We should include the exception message here and remove the "not found" part. This could happen if you don't have read permissions on the file.

2024-03-19 16:08 UTC, chenqi0805 approved these changes

2024-03-20 17:28 UTC, dlvenable approved these changes

2024-03-20 21:35 UTC, merged