Fix count aggregation exemplar data
opensearch-project/data-prepper pull request #4341
Opened 2024-03-26 23:56 UTC by kkondaka

### Description
Count aggregation incorrectly maintains a global value for exemplars. Exemplars should be maintained per `groupState`.
This change fixes it and maintains a different exemplar for different aggregate groups.

 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [X ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [X ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-03-28 18:41 UTC, chenqi0805 submitted a review, later dismissed

2024-03-28 20:51 UTC, dlvenable requested changes

2024-03-28 20:51 UTC, dlvenable commented on data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateAction.java
> -            exemplarList = new ArrayList<>();
We should remove this field and make it a local only.

2024-03-28 20:52 UTC, dlvenable commented on data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateAction.java
> -            exemplarList = new ArrayList<>();
Actually, you can just remove the field. It should now be unused.

2024-03-28 21:52 UTC, dlvenable submitted a review, later dismissed
The changes look good. I noticed the Gradle builds were failing in the previous commit.

2024-04-01 14:15 UTC, dlvenable approved these changes

2024-04-01 19:02 UTC, chenqi0805 approved these changes

2024-04-01 19:12 UTC, merged