MAINT: use authentication for basic credentials in opensearch source
opensearch-project/data-prepper pull request #4435
Opened 2024-04-17 23:01 UTC by chenqi0805

### Description
This PR deprecates username and password at the top level config and wrap them into authentication:

```
opensearch:
    authentication:
        username:
        password
```
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-04-18 16:50 UTC, oeyh approved these changes

2024-04-18 21:23 UTC, dlvenable requested changes
Similar to #4438, I'm not sure I see this as adding clarity or value to users. I understand why we nest some fields because there is a certain context necessary to add clarity. But, username and password are ubiquitous and clear.

2024-04-24 14:58 UTC, dlvenable approved these changes

2024-04-24 17:47 UTC, oeyh approved these changes

2024-04-24 19:39 UTC, merged