MAINT: allow latest schema version if not specified in confluent schema
opensearch-project/data-prepper pull request #4453
Opened 2024-04-23 19:40 UTC by chenqi0805

### Description
This PR fixes the requirement to specify schema version in confluent schema type:

current
```
kafka:
      topics:
        - name: "topic_4"
          group_id: "groupdID1"
      bootstrap_servers:
        - ...
      schema:
        type: confluent
        registry_url: https://psrc-m5k9x.us-west-2.aws.confluent.cloud
        version: 1 # <- required previously
```
after this change:
```
kafka:
      topics:
        - name: "topic_4"
          group_id: "groupdID1"
      bootstrap_servers:
        - ...
      schema:
        type: confluent
        registry_url: https://psrc-m5k9x.us-west-2.aws.confluent.cloud
```
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-04-23 23:15 UTC, dlvenable requested changes

2024-04-23 23:15 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
> +        final SchemaConfig schemaConfig = sourceConfig.getSchemaConfig();
Can we combine this code with the code above?

2024-04-24 15:23 UTC, dlvenable approved these changes

2024-04-24 16:07 UTC, oeyh approved these changes

2024-04-24 16:13 UTC, merged