Address route and subpipeline for pipeline tranformation
opensearch-project/data-prepper pull request #4528
Opened 2024-05-11 03:41 UTC by srikanthjg

### Description
Address route and subpipeline for pipeline tranformation.
1. PipelineModel uses route and routes as alias, which needs to be addressed in the transformation. 
Routes or route (defined as alias in Pipeline Model) will be always be transformed to route in json , as route will be primarily picked in pipelineModel when converting model to json or the other way round.

2. Subpipelines within one pipeline was addressed in the transformation.
Earlier, subpipelines were using the untransformed pipeline name. Made changes to make it pick the transformed pipeline name.

 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-05-11 16:50 UTC, dinujoh commented
> Routes or route (defined as alias in Pipeline Model) will be always be transformed to route in json

We should always transform it to routes.

2024-05-13 00:26 UTC, sharraj commented on data-prepper-pipeline-parser/src/main/resources/templates/documentdb-template.yaml
> +    route: "<<$.<<pipeline-name>>.route>>" # In placeholder, routes or route (defined as alias) will be transformed to route in json as route will be primarily picked in pipelineModel.
Always transform to routes

2024-05-13 00:27 UTC, sharraj commented on data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-route-expected.yaml
> +  route:
We should not use this example. Use example with routes at both places.

2024-05-13 00:28 UTC, sharraj commented on data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-route-expected.yaml
> +  route:
Same as previous comment.

2024-05-13 00:28 UTC, sharraj commented on data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-routes-expected.yaml
> +  route:
same as previous comment

2024-05-13 00:28 UTC, sharraj commented on data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-routes-expected.yaml
> +  route:
same as previous comment.

2024-05-13 00:28 UTC, sharraj commented on data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-subpipelines-routes-expected.yaml
> +  route:
same as previous comment.

2024-05-13 00:29 UTC, sharraj commented on data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-subpipelines-routes-expected.yaml
> +  route:
same as previous comment.

2024-05-13 00:29 UTC, sharraj commented on docs/pipeline_configuration_transformation.md
> +route: "<<$.<<pipeline-name>>.route>>"
We can remove this.

2024-05-13 17:32 UTC, dinujoh submitted a review, later dismissed

2024-05-13 17:33 UTC, dinujoh commented on data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/transformer/DynamicConfigTransformer.java
> +        pipelineJson = objectMapper.writeValueAsString(pipeline);
nit: inline this

2024-05-13 17:34 UTC, dinujoh commented on data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/transformer/DynamicConfigTransformer.java
> +        String parentPath = SUBPIPELINE_PATH;
nit: this variable declaration is not needed

2024-05-13 17:34 UTC, dinujoh commented on data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/transformer/DynamicConfigTransformer.java
> +                        String pipelineJson = null;
this declaration can be inline.

2024-05-13 17:54 UTC, kkondaka submitted a review, later dismissed

2024-05-13 19:28 UTC, dinujoh approved these changes

2024-05-13 20:19 UTC, dlvenable requested changes

2024-05-13 20:19 UTC, dlvenable commented on data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/transformer/DynamicConfigTransformer.java
> +    private static final String SUBPIPELINE_PATH = "$.source.pipeline";
Sub-pipelines aren't really a concept in Data Prepper. We can also give this a clearer name. e.g. `SOURCE_PIPELINE_PATH`.

2024-05-13 20:19 UTC, dlvenable commented on data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-subpipelines-routes-expected.yaml
Let's rename this to drop the "sub" from "subpipelines". Just use "pipelines."

2024-05-13 22:34 UTC, srikanthjg commented on data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-subpipelines-routes-expected.yaml
pipelines can mean 2 pipelines that are dis joint or pipelines that branch out of one main pipeline, by sub pipelines, i wanted to keep it specific to pipelines that branch out from one main pipeline.

2024-05-13 22:57 UTC, dlvenable approved these changes

2024-05-13 22:57 UTC, dlvenable commented on data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-subpipelines-routes-expected.yaml
> pipelines can mean 2 pipelines that are dis joint or pipelines that branch out of one main pipeline, by sub pipelines, i wanted to keep it specific to pipelines that branch out from one main pipeline.

Thanks for clarifying that. As long as we use it for branching, this can be ok.

2024-05-13 22:58 UTC, merged