Change log for version 2.8
opensearch-project/data-prepper pull request #4539
Opened 2024-05-14 22:02 UTC by kkondaka

### Description
Change log for version 2.8
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-05-15 22:36 UTC, dlvenable approved these changes

2024-05-15 22:37 UTC, dlvenable requested changes
@kkondaka , We've had some more recent changes and will need to regenerate this.

2024-05-16 15:49 UTC, dlvenable requested changes
@kkondaka , These commits appear to be on `main`. They don't match what I see on `2.8`:

https://github.com/opensearch-project/data-prepper/commits/2.8/

2024-05-16 15:51 UTC, kkondaka commented
Oops. Right. I did it on main. Let me redo it

2024-05-16 16:33 UTC, dlvenable approved these changes

2024-05-16 17:03 UTC, merged