Add support for Kafka headers and timestamp in the Kafka Source
opensearch-project/data-prepper pull request #4566
Opened 2024-05-22 23:04 UTC by kkondaka

### Description
Add support for Kafka headers and timestamp in the Kafka Source.
If the consumer Record has any headers, they are included in the event. Similarly, timestamp is included in the event.
 
### Issues Resolved
Resolves #4565 
 
### Check List
- [X ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-05-23 16:05 UTC, KarstenSchnitter reviewed
There is a minor typo, that might cause the test failures.
What about support for this in the producer as well?

2024-05-23 16:05 UTC, KarstenSchnitter commented on data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java
> +        data.put("kakfa"+kafkaTimestampKey+"_timestamp", consumerRecord.timestamp());
```suggestion
        data.put("kafka"+kafkaTimestampKey+"_timestamp", consumerRecord.timestamp());
```

2024-05-24 17:20 UTC, dlvenable requested changes

2024-05-24 20:45 UTC, graytaylor0 approved these changes

2024-05-29 15:19 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java
> +        data.put("kafka"+kafkaTimestampKey+"_timestamp", consumerRecord.timestamp());
Could we have?

```
kafka_timestamp_type
kafka_timestamp
```

2024-05-29 15:35 UTC, kkondaka commented on data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java
> +        data.put("kafka"+kafkaTimestampKey+"_timestamp", consumerRecord.timestamp());
I can make that change. Do you think that's better?

2024-05-30 14:11 UTC, dlvenable approved these changes
Thanks for this useful addition, @kkondaka !

2024-05-30 16:09 UTC, graytaylor0 approved these changes

2024-05-30 16:31 UTC, merged