Refactor http source functionality for supporting a new OpenSearch API source in DataPrepper
opensearch-project/data-prepper pull request #4570
Opened 2024-05-28 21:08 UTC by sb2k16

### Description

In order for DataPrepper to support all OpenSearch Document API(s), we need to build a new source similar to the existing `http` source. As a first step, this pull request is intended to refactor some of the existing functionalities in `http` source including ssl support, certificate handling, throttling functionality and request rejection handling to a new `http-source-common` package under `data-prepper-plugins`. 
 
### Issues Resolved
Resolves #248
 
### Check List
- [X] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
- [X] New functionality has javadoc added
- [X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-06-03 15:24 UTC, dlvenable requested changes
Thank you @sb2k16 for this great contribution! I have a few comments, but otherwise it looks good.

2024-06-03 15:24 UTC, dlvenable commented on data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceConfigTest.java
> +    private void reflectivelySetField(final HTTPSourceConfig httpSourceConfig, final String fieldName, final Object value) throws NoSuchFieldException, IllegalAccessException {
This was added as a test helper. Let's use that:

https://github.com/opensearch-project/data-prepper/blob/6648d9fea792cfca889c69f62ce50af6ee12392a/data-prepper-test-common/src/main/java/org/opensearch/dataprepper/test/helper/ReflectivelySetField.java#L29-L38

2024-06-03 15:24 UTC, dlvenable commented on data-prepper-plugins/http-source-common/src/main/java/org/opensearch/dataprepper/http/HttpServerConfig.java
> +public class HttpServerConfig {
Let's make this an interface. Then you can create a `BaseHttpServerConfig` that implements the interface and has the same implementation that you have here.

We may find that we want a different set of default values or even different configurations between sources. So decoupling the usage of this interface from the concrete configuration will allow these to vary as needed.

2024-06-03 15:45 UTC, dlvenable requested changes

2024-06-03 15:45 UTC, dlvenable commented on data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
>      public CompressionOption getCompression() {
Do we need to add this to `HttpServerConfig`? How will it be used if it is only here?

2024-06-04 18:07 UTC, dlvenable requested changes

2024-06-04 18:07 UTC, dlvenable commented on data-prepper-plugins/http-source-common/build.gradle
> +    implementation project(':data-prepper-test-common')
Please make this `testImplementation` and move toward the bottom to sit with the other `testImplementation` dependencies.

2024-06-04 18:08 UTC, dlvenable requested changes

2024-06-04 18:08 UTC, dlvenable commented on data-prepper-plugins/http-source/build.gradle
> +    implementation project(':data-prepper-test-common')
Please make this `testImplementation` and move to set with the other `testImplementation` dependencies a few lines below.

2024-06-04 20:48 UTC, kkondaka submitted a review, later dismissed

2024-06-04 22:09 UTC, dlvenable approved these changes

2024-06-04 22:31 UTC, kkondaka approved these changes

2024-06-04 23:49 UTC, merged