FIX: decouple msk auth from glue auth in KafkaSource
opensearch-project/data-prepper pull request #4613
Opened 2024-06-08 03:55 UTC by chenqi0805

### Description
This PR decouples MSK aws auth from that for AWS Glue
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-06-10 22:11 UTC, dlvenable requested changes
Thanks @chenqi0805 for this change! Overall it looks good. I have a few comments first.

2024-06-10 22:11 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSecurityConfigurerTest.java
> +        assertThat(props.getProperty("sasl.mechanism"), is("AWS_MSK_IAM"));
Should there be an assertion for the `sasl.jaas.config` here as well?

2024-06-10 22:11 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/src/test/resources/kafka-pipeline-bootstrap-servers-sasl-iam-role.yaml
> +          sts_role_arn: sts_role_arn
Can you use something more unique to help ensure the assertion in the test is unique. Maybe `test_sasl_iam_sts_role`?

2024-06-10 22:11 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSecurityConfigurerTest.java
> +        final String testMSKEndpoint = "bootstrap-server-string";
Maybe this a random UUID.

2024-06-10 22:11 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSecurityConfigurerTest.java
> +        final String testMSKEndpoint = "bootstrap-server-string";
Also, make this a random UUID string.

2024-06-10 22:11 UTC, dlvenable commented on data-prepper-plugins/kafka-plugins/src/test/resources/kafka-pipeline-msk-sasl-plain.yaml
> +              username: username
Use some values that are more unique: `test_sasl_username` and `test_sasl_password` would work.

2024-06-12 17:09 UTC, dlvenable approved these changes

2024-06-12 19:02 UTC, kkondaka approved these changes

2024-06-12 19:46 UTC, merged