MAINT: backfill doc in json property description for otel_metrics
opensearch-project/data-prepper pull request #4722
Opened 2024-07-10 22:06 UTC by chenqi0805

### Description
This PR serves as the starter for backfill [plugin setting config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/otel_metrics) into @JsonPropertyDescription so that a complete json schema can be generated.
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-07-11 14:53 UTC, dlvenable requested changes

2024-07-11 14:53 UTC, dlvenable commented on data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OtelMetricsRawProcessorConfig.java
> +@JsonClassDescription("https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/otel-metrics/#configuration")
Remove this. We can auto-generate it later.

2024-07-12 14:38 UTC, dlvenable approved these changes

2024-07-12 16:35 UTC, oeyh approved these changes

2024-07-13 05:30 UTC, merged