Support BigDecimal data type in expressions
opensearch-project/data-prepper pull request #4930
Opened 2024-09-10 07:19 UTC by kkondaka

### Description
Support BigDecimal data type in expressions
 
### Issues Resolved
Resolves #4817 
 
### Check List
- [ X] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-09-10 15:22 UTC, oeyh reviewed
Thanks for working on this! 

Looks good other than an unused import.

2024-09-10 15:22 UTC, oeyh commented on data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ParseTreeCoercionService.java
> +import java.math.BigDecimal;
This is unused.

2024-09-10 16:33 UTC, dlvenable requested changes

2024-09-10 16:33 UTC, dlvenable commented on data-prepper-expression/src/main/antlr/DataPrepperExpression.g4
> +BIG_DECIMAL: 'big_decimal';
Didn't we use the term `decimal` to be consistent with OpenSearch?

2024-09-13 00:39 UTC, oeyh approved these changes

2024-09-27 14:34 UTC, dlvenable approved these changes

2024-09-27 14:34 UTC, dlvenable commented on data-prepper-expression/src/main/antlr/DataPrepperExpression.g4
> +BIG_DECIMAL: 'big_decimal';
We did use `big_decimal`, but that was already released. We should fix this by adding an alias in another PR.

2024-09-27 16:04 UTC, merged