Add retry to make sure source is not shutdown when exceptions are thrown on the main thread
opensearch-project/data-prepper pull request #5029
Opened 2024-10-08 00:19 UTC by sb2k16

### Description
It has been observed that If the pipeline role is missing Kinesis permissions, the source throws an exception resulting in a shutdown of the pipeline.
The fix is to add retry based on 2 configurations in KinesisSource:
  - max_initialization_attempts - to allow the customer to continue retry to initialize the source 
  - initialization_backoff_time - wait between retry calls 

This should help to make sure that the pipeline is not terminated when permissions are missing. With updated permissions, the pipeline should continue to initialize and function properly.
 
### Issues Resolved
Resolves #1082 
 
### Check List
- [X] New functionality includes testing.
- [X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-10-08 19:00 UTC, dlvenable requested changes

2024-10-08 19:00 UTC, dlvenable commented on data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisService.java
> +                    LOG.debug("Interrupted exception!");
```suggestion
                    LOG.debug("Interrupted exception.");
```

2024-10-08 21:40 UTC, sb2k16 commented on data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisService.java
> +            return;
Thanks @dlvenable . I have addressed this.

2024-10-08 21:40 UTC, sb2k16 commented on data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisService.java
> +            LOG.info("Scheduler not initialized!!");
Thanks @dlvenable . I have addressed this.

2024-10-09 16:27 UTC, dlvenable approved these changes

2024-10-10 23:47 UTC, kkondaka approved these changes

2024-10-11 02:47 UTC, merged