ENH: backfill @AlsoRequired annotation to processor attributes
opensearch-project/data-prepper pull request #5086
Opened 2024-10-18 18:02 UTC by chenqi0805

### Description
This PR backfills @AlsoRequired annotation to processor attributes for schema generation purpose:

aggregate:
- [ ] aggregated_events_tag is required when output_unaggregated_events is non null.
flatten:
- [ ] remove_bracket can only be set to true if remove_list_indices is true
key_value:
- [ ] field_split_characters and field_delimiter_regex are mutually exclusive
- [ ] field_delimiter_regex are mutually exclusive with field_split_characters and value_grouping
- [ ] value_split_characters and key_value_delimiter_regex are mutually exclusive
- [ ] string_literal_character depends on value_grouping enabled
add_entry:
- [ ] string_literal_character depends on value_grouping enabled
- [ ] key and metadata_key are mutually exclusive
- [ ] format, value and value_expression are mutually exclusive
- [ ] overwrite_if_key_exists and append_if_key_exists are mutually exclusive
convert_entry:
- [ ] key and keys are mutually exclusive
copy_value
- [ ] from_list and to_list are mutually dependent
split string:
- [ ] delimiter_regex and delimiter are mutually exclusive
split event:
- [ ] delimiter_regex and delimiter are mutually exclusive

 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-10-18 19:17 UTC, shenkw1 requested changes

2024-10-18 19:17 UTC, shenkw1 commented on data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
>      @JsonProperty(value = "recursive", defaultValue = "false")
recursive config has a restriction where remove_brackets must be false, skip_duplicate_values is always true, and whitespace is always strict

2024-10-18 19:45 UTC, shenkw1 approved these changes

2024-10-18 20:43 UTC, oeyh reviewed
There's a merge conflict. 

There're some other cases that the annotation can be added:
list_to_map: key is required if `use_source_key` is false
translate: under targets, map and regex are mutually exclusive

2024-10-18 21:44 UTC, shenkw1 approved these changes

2024-10-21 14:57 UTC, oeyh approved these changes

2024-10-21 15:03 UTC, merged