Escape control characters
opensearch-project/data-prepper pull request #5177
Opened 2024-11-08 12:49 UTC by paulsasi

### Description
Escapes control characters for the DynamoDB source.
 
### Issues Resolved
Resolves #5027
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-11-12 21:06 UTC, dlvenable requested changes

2024-11-12 21:06 UTC, dlvenable commented on data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverter.java
> +                sanitizedStringBuilder.append(String.format("\\u%04X", (int) c));
Is there a way to write this string without calling `String.format` to avoid the performance penalty?

2024-11-12 21:06 UTC, dlvenable commented on data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverter.java
> +            if (Character.isISOControl(c) && c != '\t' && c != '\n' && c != '\r') {
I tend to think that we should have this as an optional configuration to avoid breaking any existing behavior. Thoughts?

2024-11-12 21:08 UTC, dlvenable requested changes

2024-11-12 21:08 UTC, dlvenable commented on data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java
> +            "String with some control characters: \0\1\2\3\4\5\6\7\10\11\12\13\14\15\16\17\20\21\22\23\24\25\26\27\28\29\30\31\127\b\t\n\f\r"
We should also have a test that provides both the input and the expected output to verify that the result is what we want.

2024-11-20 12:13 UTC, voronin-ilya commented
It looks like there is a flag for the Jackson parser that will simply allow it to process control characters. JFYI.
<img width="957" alt="image" src="https://github.com/user-attachments/assets/7e1e68aa-d5bc-458b-b024-387dc1923c28">

2024-11-21 06:18 UTC, closed without merging