Fix lambda metrics
opensearch-project/data-prepper pull request #5201
Opened 2024-11-18 20:39 UTC by kkondaka

### Description
Fix lambda metrics. 
1. Fix PluginMetrics to allow changing name
2. Add request and response payload metrics in the processor
 
### Issues Resolved
Resolves #[Issue number to be closed when this PR is merged]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-11-18 21:32 UTC, dlvenable requested changes

2024-11-18 21:32 UTC, dlvenable commented on data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/AbstractSink.java
> +    protected String getName(final PluginSetting pluginSetting) {
I don't think we should change `AbstractSink` for renaming. Rather, let the concrete sink pass in the `PluginMetrics`. Then handle the renaming in the `LambdaSink` directly.


```
super(pluginSetting, PluginMettrics.fromPluginSetting(pluginSetting));
```

2024-11-19 17:20 UTC, san81 approved these changes

2024-11-19 20:28 UTC, dlvenable requested changes

2024-11-19 20:28 UTC, dlvenable commented on data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSink.java
> +          continue;
Please remove this `continue`. It is likely to cause bugs later on.

2024-11-19 20:28 UTC, dlvenable commented on data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessor.java
> +                    continue;
Please remove this `continue` and use the catch to increment. This approach is likely to lead to future code bugs.

2024-11-19 20:41 UTC, dlvenable approved these changes

2024-11-19 20:41 UTC, merged