Kds stream api changes
opensearch-project/data-prepper pull request #5239
Opened 2024-12-02 20:38 UTC by sb2k16

### Description
This PR is to use the `DescribeStreamSummary` API to get the stream identifier instead of the `DescribeStream`. It also includes handling retries using an exponential backoff strategy. 
 
### Issues Resolved
Resolves #1082 
 
### Check List
- [X] New functionality includes testing.
- [X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2024-12-02 22:39 UTC, dlvenable requested changes

2024-12-02 22:39 UTC, dlvenable commented on data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisClientAPIHandler.java
> +public class KinesisClientAPIHandler {
Rename to `KinesisClientApiHandler` to promote consistency.

2024-12-02 22:39 UTC, dlvenable commented on data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisClientAPIHandler.java
> +                DescribeStreamSummaryRequest describeStreamSummaryRequest = DescribeStreamSummaryRequest.builder()
You can move this outside of the `while` loop so that you don't have to recreate it.

2024-12-02 22:39 UTC, dlvenable commented on data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisClientAPIHandler.java
> +                DescribeStreamSummaryResponse response = kinesisClient.describeStreamSummary(describeStreamSummaryRequest).join();
Does this require different `kinesis:` permissions?

2024-12-03 15:54 UTC, dlvenable requested changes

2024-12-03 15:54 UTC, dlvenable commented on data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisClientAPIHandler.java
> +            } catch (Exception ex) {
Let's catch some known exceptions that the Kinesis client throws for server or client errors and log those without the stack trace.

e.g.

```
catch (GenericKinesisException ex) {
  log.error("Failed to describe stream summary for stream {} with error {}. The kinesis source will retry.",
     streamName, ex.getMessage());
} catch (GenericKinesisException ex) {
  log.error("Failed to describe stream summary for stream {}. The kinesis source will retry.",
     streamName, ex);
}
```

2024-12-03 15:54 UTC, dlvenable commented on data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisClientAPIHandler.java
> +            Thread.currentThread().interrupt();
Why are you interrupting the current thread?

2024-12-03 15:54 UTC, dlvenable commented on data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisClientAPIHandler.java
> +            log.error("Thread is interrupted while polling SQS with retry.", e);
```suggestion
            log.error("Thread is interrupted while polling Kinesis with retry.", e);
```

2024-12-03 15:54 UTC, dlvenable commented on data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisClientAPIHandlerTest.java
> +    private static final List<String> STREAMS_LIST = ImmutableList.of("stream-1", "stream-2", "stream-3");
I'd recommend making this a variable you initialize in `@BeforeEach`. Also, you could even have `@Nested` classes to test the scenario of 0 and 1 streams as well.

Also, you can use Java's `List.of()` which is also immutable.

2024-12-10 20:24 UTC, kkondaka approved these changes

2024-12-10 20:40 UTC, merged