Remove code tags from processor names, fill in default values
opensearch-project/data-prepper pull request #5278
Opened 2024-12-23 18:31 UTC by shenkw1

### Description
Remove code tags from processor names in processor descriptions, fill in default values in the anomaly detector random cut forest mode config.
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2025-01-02 17:47 UTC, chenqi0805 approved these changes

2025-01-06 17:37 UTC, divbok approved these changes

2025-01-06 17:48 UTC, dlvenable requested changes
Why are we removing these `<code>` blocks? They are important for the documentation?

For other downstream usage, you can use tooling to remove these blocks.

2025-01-06 21:45 UTC, chenqi0805 approved these changes

2025-01-07 16:22 UTC, merged