migrating demo sample application to use opensearch and opensearch da…
opensearch-project/data-prepper pull request #666
Opened 2021-11-30 19:46 UTC by cmanning09

…shboards instead of ODFE and kibana

Signed-off-by: Christopher Manning <cmanning09@users.noreply.github.com>

### Description
While preparing for a demo I noticed the use of ODFE and kibana in a sample application. This change migrates those resources to the OpenSearch and OpenSearch Dashboards. I am leveraging existing docker configurations from other
example apps.
 
### Issues Resolved
N/A
 
### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2021-11-30 20:04 UTC, dlvenable requested changes
Thanks for making these changes! There is a `README.md` file in the same directory which I'd like to see updated as part of this PR. It references Open Distro, ElasticSearch, and Kibana.

2021-11-30 20:05 UTC, cmanning09 commented
> Thanks for making these changes! There is a `README.md` file in the same directory which I'd like to see updated as part of this PR. It references Open Distro, ElasticSearch, and Kibana.

Will do

2021-11-30 20:34 UTC, dlvenable commented on examples/trace-analytics-sample-app/README.md
> +- OpenSearch -> 9200,9300
I think this is referring to the Docker container name, which is `opensearch`.

2021-11-30 23:05 UTC, dlvenable approved these changes

2021-11-30 23:09 UTC, dlvenable commented
This PR partially resolves #639.

2021-12-01 15:39 UTC, cmanning09 commented
> This PR partially resolves #639.

Ah, I missed that you opened an issue for this. Thanks!

2021-12-02 23:45 UTC, chenqi0805 approved these changes

2021-12-02 23:59 UTC, dinujoh approved these changes

2021-12-03 13:03 UTC, merged