Example: ECS FireLens integration
opensearch-project/data-prepper pull request #704
Opened 2021-12-06 15:58 UTC by chenqi0805

### Description
This PR adds a nginx example to demo the integration of data-prepper service with [ECS FireLens](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html).
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2021-12-06 17:29 UTC, dlvenable requested changes
Thanks for creating this example! This is a useful scenario to have documented.

2021-12-06 21:24 UTC, chenqi0805 commented on examples/log-ingestion-ecs-firelens/README.md
> +* To create a task definition using the classic ECS console, please refer [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-task-definition-classic.html).
For some reason, ECS new console does not have `configure via JSON` option for create task definition.

2021-12-06 21:35 UTC, chenqi0805 commented on examples/log-ingestion-ecs-firelens/README.md
> +* To create a task definition using the classic ECS console, please refer [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-task-definition-classic.html).
@dlvenable Despite that, in the updates, I still included the new console link.

2021-12-06 23:03 UTC, dlvenable approved these changes
Thanks! It looks good.

2021-12-07 15:45 UTC, dinujoh approved these changes

2021-12-07 15:47 UTC, sshivanii approved these changes

2021-12-07 22:36 UTC, merged