Change JacksonEvent isNumeric to StringUtils.isNumeric
opensearch-project/data-prepper pull request #711
Opened 2021-12-09 23:41 UTC by graytaylor0

### Description
Change to StringUtils.isNumeric
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2021-12-09 23:53 UTC, cmanning09 requested changes
I think the change to use isNumeric looks good but you have included commits which are already squashed and merged into mainline. Please rebase you branch.

2021-12-10 15:43 UTC, dlvenable approved these changes

2021-12-10 15:43 UTC, dlvenable commented on data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/JacksonEvent.java
> -    private boolean isNumeric(final String str) {
I'd probably keep `isNumeric` and make this call `StringUtils.isNumeric`. This way, there is one approach within this class. But, this is still great. Thanks!

2021-12-10 19:26 UTC, cmanning09 approved these changes

2021-12-10 19:28 UTC, merged