Release notes
opensearch-project/data-prepper pull request #743
Opened 2021-12-14 16:35 UTC by cmanning09

### Description
Following OpenSearch release note format. I used [git-release-notes](https://github.com/ariatemplates/git-release-notes) to generate the release notes. This PR is to merge the change into 1.2 branch. 

Note: I accidentally closed the original PR (#653) by updating my 1.2 branch. 
 
### Issues Resolved
Resolves #618 
 
### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2021-12-14 16:42 UTC, sshivanii submitted a review, later dismissed

2021-12-14 19:10 UTC, dlvenable requested changes
Can we set the date to the Dec 15? We are looking in good shape for that date.

2021-12-14 20:04 UTC, graytaylor0 reviewed
Looks good. Just some minor comments.

2021-12-14 20:04 UTC, graytaylor0 commented on release/release-notes/data-prepper.release-notes-1.2.0.md
> +* File Source file type is now configurable and support parse JSON files. The default remains plain text.  ([#601](https://github.com/opensearch-project/data-prepper/pull/601)),
typo: should be "supports parsing"

2021-12-14 20:04 UTC, graytaylor0 commented on release/release-notes/data-prepper.release-notes-1.2.0.md
> +* Data Prepper core APIs not support basic HTTP Authentication, Docker image's core API's are now secure by default ([#558](https://github.com/opensearch-project/data-prepper/pull/558)), ([#561](http
typo: "now" instead of "not"

2021-12-14 20:04 UTC, graytaylor0 commented on release/release-notes/data-prepper.release-notes-1.2.0.md
> +* The FileSource supports the new event model ([#](https://github.com/opensearch-project/data-prepper/pull/601))
Nit: FileSource supports Objects similarly to StdOutSink

2021-12-14 20:05 UTC, dlvenable commented on release/release-notes/data-prepper.release-notes-1.2.0.md
> +* Grok Processor for processing unstructured data with grok pattern matching. ([#302](https://github.com/opensearch-project/data-prepper/pull/302)), ([#324](https://github.com/opensearch-project/data
We should not be documenting that here.

2021-12-14 20:13 UTC, cmanning09 commented on release/release-notes/data-prepper.release-notes-1.2.0.md
> +* The FileSource supports the new event model ([#](https://github.com/opensearch-project/data-prepper/pull/601))
From a CX perspective it supports the new model.

2021-12-15 15:27 UTC, dlvenable approved these changes

2021-12-15 15:59 UTC, sshivanii approved these changes

2021-12-15 17:59 UTC, merged