Add PipelineDescription object to be passed to @DataPrepperPluginConstructor
opensearch-project/data-prepper pull request #825
Opened 2022-01-05 17:14 UTC by graytaylor0

Signed-off-by: Taylor Gray <33740195+graytaylor0@users.noreply.github.com>

### Description
* Adds `PipelineDescription` interface to allow passing of pipeline details to the plugins that belong to that pipeline
* Only `PluginSetting` implements this interface. A DefaultPipelineDescription could be created in the future to isolate the PipelineDescription information (i.e. with the configuration settings in `PluginSetting`).
* `PipelineDescription` is now an optional parameter to use with the `@DataPrepperPluginConstructor`
 
### Issues Resolved
closes #771
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2022-01-05 18:03 UTC, dlvenable requested changes
Looks great! I have one small comment regarding `@since`.

2022-01-05 18:03 UTC, dlvenable commented on data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PipelineDescription.java
> +public interface PipelineDescription {
Please add `@since 1.3` to the Javadocs since this is a public interface.

I also think it is good to include it on the methods below.

2022-01-05 19:29 UTC, dlvenable approved these changes

2022-01-06 16:42 UTC, sbayer55 approved these changes
Nice interface idea.

2022-01-06 16:58 UTC, merged