Add Drop Mapping
opensearch-project/data-prepper pull request #841
Opened 2022-01-06 21:23 UTC by dapowers87

Signed-off-by: David Powers <ddpowers@amazon.com>

### Description
Creates a mapping between Logstash's Drop filter and Data Prepper's DropEventProcessor

 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

2022-01-06 21:28 UTC, graytaylor0 commented on data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/drop.mapping.yaml
> +pluginName: drop
Shouldn't there be a mapping somewhere from the name `drop` to `drop_events`

2022-01-06 21:31 UTC, sshivanii commented on data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/drop.mapping.yaml
> +pluginName: drop
`pluginName` should be `drop_events`

2022-01-07 16:26 UTC, dapowers87 commented on data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/drop.mapping.yaml
> +pluginName: drop
Thanks, I got mixed up.

2022-01-07 17:58 UTC, dlvenable requested changes
Please also update the integration tests. You can either add a new file and expected result, or just add it into an existing file (and still update the expected result).

2022-01-07 17:59 UTC, dlvenable commented
See this documentation on integration testing:
https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/LogstashConfigConverterIT.java#L31-L43

2022-01-10 16:31 UTC, dlvenable approved these changes
Thanks!

2022-01-10 18:59 UTC, sshivanii approved these changes
LGTM

2022-01-10 18:59 UTC, merged